packages/php7.1/APKBUILD, packages/php7.2/APKBUILD, packages/php7.3/APKBUILD
https://twitter.com/official_php/status/1103677481368936449
=> 7.1.27 / 7.2.16 / 7.3.3

packages/php7.1/APKBUILD, packages/php7.2/APKBUILD, packages/php7.3/APKBUILD
php 7.1.30
php 7.2.19
php 7.3.6
=> Security updates 2019-05

packages/php7.2/APKBUILD, packages/php7.3/APKBUILD
=> Bugfix release 2019-07

packages/php7.1/APKBUILD, packages/php7.2/APKBUILD, packages/php7.3/APKBUILD
- php 7.1.31
- php 7.2.21
- php 7.3.8
=> PHP update 2019-07

packages/php7.1/APKBUILD, packages/php7.2/APKBUILD, packages/php7.3/APKBUILD
- php 7.1.32
- php 7.2.22
- php 7.3.9
=> Security update 2019-08-30

packages/php7.2/APKBUILD, packages/php7.3/APKBUILD
* PHP 7.2.24 https://www.php.net/archive/2019.php#2019-10-24-2
* PHP 7.3.11 https://www.php.net/archive/2019.php#2019-10-24-1
=> PHP security update 2019-10

packages/php7.2/APKBUILD, packages/php7.2/iconv.c.patch, packages/php7.3/APKBUILD, packages/php7.3/iconv.c.patch
=> PHP update 2019-11

packages/php7.2/APKBUILD, packages/php7.3/APKBUILD
=> Security update 2019-12

packages/php7.2/APKBUILD, packages/php7.3/APKBUILD, packages/php7.4/APKBUILD
* PHP 7.2.28
* PHP 7.3.15
* PHP 7.4.3
=> Security update 02-2020

packages/php7.2/APKBUILD, packages/php7.3/APKBUILD, packages/php7.4/APKBUILD
- PHP 7.2.30
- PHP 7.3.17
- PHP 7.4.5
=> Security updates 2020-04

packages/php7.2/APKBUILD, packages/php7.3/APKBUILD, packages/php7.4/APKBUILD
- php 7.2.31
- php 7.3.18
- php 7.4.6
=> Security update 2020-05

packages/php7.3/APKBUILD, packages/php7.4/APKBUILD
=> PHP Security update 2020-06

packages/php7.2/APKBUILD, packages/php7.3/APKBUILD, packages/php7.4/APKBUILD
* PHP 7.2.33
* PHP 7.3.21
* PHP 7.4.9
=> PHP update 2020-08

packages/php7.3/APKBUILD, packages/php7.4/APKBUILD
=> PHP Update 2020-09

packages/php7.3/APKBUILD, packages/php7.4/APKBUILD
=> PHP Update 2020-10

packages/php7.3/APKBUILD, packages/php7.4/APKBUILD
=> PHP Security release 2020-11

packages/php7.3/APKBUILD, packages/php7.4/APKBUILD, packages/php8.0/APKBUILD
* PHP 7.3.26
* PHP 7.4.14
* PHP 8.0.1
=> PHP update 2021-01

packages/php7.4/APKBUILD, packages/php8.0/APKBUILD
=> PHP Update 2021-03

packages/php7.4/APKBUILD, packages/php8.0/APKBUILD
=> PHP update 2021-05

packages/php7.4/APKBUILD, packages/php8.0/APKBUILD
=> PHP update 2021-06

packages/php7.3/APKBUILD, packages/php7.4/APKBUILD, packages/php8.0/APKBUILD
- PHP 8.0.8
- PHP 7.4.21
- PHP 7.3.29
=> 2021-07 Update

packages/php7.4/APKBUILD, packages/php8.0/APKBUILD
=> PHP update 2021-08

packages/php7.3/APKBUILD, packages/php7.4/APKBUILD, packages/php8.0/APKBUILD
- PHP 8.0.10
- PHP 7.4.23
- PHP 7.3.30
=> PHP update 2021-08-28

packages/php7.3/APKBUILD, packages/php7.4/APKBUILD
=> PHP Update 2021-11

packages/php7.4/APKBUILD, packages/php8.0/APKBUILD, packages/php8.1/APKBUILD
- PHP 8.1.1
- PHP 8.0.14
- PHP 7.4.27
=> PHP Update 2021-12

packages/php8.0/APKBUILD, packages/php8.1/APKBUILD
=> PHP Update 2022-01

packages/php7.4/APKBUILD, packages/php8.0/APKBUILD, packages/php8.1/APKBUILD
- PHP 8.1.3
- PHP 8.0.16
- PHP 7.4.28
=> PHP Update 2022-02

packages/php8.0/APKBUILD, packages/php8.1/APKBUILD
=> PHP Update 2022-03

packages/php7.4/APKBUILD, packages/php8.0/APKBUILD, packages/php8.1/APKBUILD
- PHP 8.1.5
- PHP 8.0.18
- PHP 7.4.29
=> PHP Updates 2022-04

packages/php8.0/APKBUILD, packages/php8.1/APKBUILD
=> PHP Update 2022-05

packages/php7.4/APKBUILD, packages/php8.0/APKBUILD, packages/php8.1/APKBUILD
* PHP 8.1.7
* PHP 8.0.20
* PHP 7.4.30
=> PHP Security Update 2022-06

packages/php8.0/APKBUILD, packages/php8.1/APKBUILD
=> PHP Updates 2022-07

packages/php8.0/APKBUILD, packages/php8.1/APKBUILD
=> PHP Update 2022-08

packages/php8.0/APKBUILD, packages/php8.1/APKBUILD
=> PHP Update 2022-09

packages/php8.0/APKBUILD
=> PHP Update 2022-10

packages/php8.0/APKBUILD, packages/php8.1/APKBUILD
=> PHP Update 2022-11

packages/php8.0/APKBUILD, packages/php8.1/APKBUILD, packages/php8.2/APKBUILD
* PHP 8.2.1
* PHP 8.1.14
* PHP 8.0.27
=> PHP security update 2023-01

packages/php8.1/APKBUILD, packages/php8.2/APKBUILD
=> PHP update 2023-02

packages/php8.0/APKBUILD, packages/php8.1/APKBUILD, packages/php8.2/APKBUILD
* PHP 8.2.3
* PHP 8.1.16
* PHP 8.0.28
=> PHP Security update 2023-02 (2)

packages/php8.1/APKBUILD, packages/php8.2/APKBUILD
=> PHP Update 2023-03

packages/php8.1/APKBUILD, packages/php8.2/APKBUILD
=> PHP Update 2023-04

packages/php8.2/APKBUILD
=> PHP Update 2023-05

packages/php8.1/APKBUILD, packages/php8.2/APKBUILD
https://php.watch/versions/8.1/gd-avif
=> Enable gd-avif

packages/php8.0/APKBUILD, packages/php8.1/APKBUILD, packages/php8.2/APKBUILD
* PHP 8.2.7
* PHP 8.1.20
* PHP 8.0.29
=> PHP Update 2023-06

packages/php8.1/APKBUILD, packages/php8.2/APKBUILD
=> PHP Update 2023-07

packages/php8.0/APKBUILD, packages/php8.1/APKBUILD
PHP Updates
- PHP 8.1.22
- PHP 8.0.30
=> PHP Update 2023-08

packages/php8.1/APKBUILD, packages/php8.2/APKBUILD
=> PHP Updates 2023-09-29

packages/php8.1/APKBUILD, packages/php8.2/APKBUILD
=> PHP update 2023-10-30

packages/php8.1/APKBUILD, packages/php8.2/APKBUILD
=> PHP Update 2023-11-28

packages/php8.1/APKBUILD, packages/php8.2/APKBUILD, packages/php8.3/APKBUILD
* PHP 8.3.1
* PHP 8.2.14
* PHP 8.1.27
=> PHP Update 2023-12

packages/php8.2/APKBUILD, packages/php8.3/APKBUILD
=> PHP Update 2024-01

build/entrypoint, packages/php7.4-spx/APKBUILD, packages/php8.0-spx/APKBUILD, packages/php8.1-spx/APKBUILD, packages/php8.2-spx/APKBUILD, packages/php8.3-spx/APKBUILD
* Update `php8.X-spx` to v0.4.15
* Add support for PHP 8.3
https://github.com/NoiseByNorthwest/php-spx/releases/tag/v0.4.15
=> Spx 0.4.15

packages/php8.2/APKBUILD, packages/php8.3/APKBUILD
=> PHP update 2024-02

packages/php8.2/APKBUILD, packages/php8.3/APKBUILD
=> PHP Update 2024-03

packages/php8.2/APKBUILD, packages/php8.3/APKBUILD
=> PHP Update 2024-04

packages/php8.2/APKBUILD, packages/php8.3/APKBUILD
=> PHP Update 2024-05

packages/php8.1/APKBUILD, packages/php8.2/APKBUILD, packages/php8.3/APKBUILD
* PHP 8.3.8
* PHP 8.2.20
* PHP 8.1.29
=> PHP Security Update 2024-06

packages/php8.2/APKBUILD, packages/php8.3/APKBUILD
=> PHP Update 2024-07

.circleci/config.yml
https://alpinelinux.org/posts/Alpine-3.20.0-released.html
=> Alpine 3.20

packages/php8.2/APKBUILD, packages/php8.3/APKBUILD
=> PHP Update 2024-08

packages/php8.0/APKBUILD, packages/php8.1/APKBUILD, packages/php8.2/APKBUILD, packages/php8.3/APKBUILD
https://serverfault.com/questions/1017932/php-fpm-notice-the-log-buffer-is-full-1024-the-access-log-request-has-been
=> Set MAX_LINE_LEGTH=8192

packages/php8.2/APKBUILD, packages/php8.3/APKBUILD
=> PHP Update 29-08-2024

packages/php8.1/APKBUILD, packages/php8.2/APKBUILD, packages/php8.3/APKBUILD
* PHP 8.3.12
* PHP 8.2.24
* PHP 8.1.30
=> PHP update 2024-09

packages/php8.1/APKBUILD, packages/php8.2/APKBUILD, packages/php8.3/APKBUILD, packages/php8.4/APKBUILD
* 8.4.1
* 8.3.14
* 8.2.26
* 8.1.31
=> PHP Upgrade 2024-11

packages/php8.2/APKBUILD, packages/php8.3/APKBUILD, packages/php8.4/APKBUILD
* PHP 8.4.2
* PHP 8.3.15
* PHP 8.2.27
=> PHP Update 2024-12

packages/php8.3/APKBUILD, packages/php8.4/APKBUILD
https://www.php.net/ChangeLog-8.php#8.4.3
https://www.php.net/ChangeLog-8.php#8.3.16
=> PHP 8.4.3 and 8.3.16

packages/php8.3/APKBUILD, packages/php8.4/APKBUILD
=> PHP Update 2025-02

packages/php8.1/APKBUILD, packages/php8.2/APKBUILD, packages/php8.3/APKBUILD, packages/php8.4/APKBUILD
* PHP 8.4.5
* PHP 8.3.19
* PHP 8.2.28
* PHP 8.1.32
=> PHP Update 2025-03

packages/php8.3/APKBUILD, packages/php8.4/APKBUILD
=> PHP Update 2025-04

packages/php8.3/APKBUILD, packages/php8.4/APKBUILD
=> PHP Update 2025-06

packages/php8.2/APKBUILD, packages/php8.3/APKBUILD, packages/php8.4/APKBUILD
* PHP 8.4.10
* PHP 8.3.23
* PHP 8.2.29
=> PHP security update 2025-07

packages/php8.3/APKBUILD, packages/php8.4/APKBUILD
=> PHP Update 2025-08

packages/php8.3/APKBUILD, packages/php8.4/APKBUILD
=> PHP Update 2025-08 (2)

packages/php8.3/APKBUILD, packages/php8.4/APKBUILD
=> PHP Update 2025-09
